//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixErp302.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUrunler
    {
        public int Id { get; set; }
        public string UrunKodu { get; set; }
        public string UrunAciklama { get; set; }
        public Nullable<int> MenseiId { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> BirimId { get; set; }
        public Nullable<int> CariId { get; set; }
    
        public virtual bBirim bBirim { get; set; }
        public virtual bKategori bKategori { get; set; }
        public virtual bMensei bMensei { get; set; }
        public virtual TblCari TblCari { get; set; }
    }
}
